version: '3.4'
networks:
  frontend:
    external: true
  backend:
    external: true

services:
  db:
    container_name: mysql-db
    image: hypriot/rpi-mysql
    env_file: /home/pi/website/config/db/.env
    volumes:
     - /home/pi/website/db/storage:/var/lib/mysql
    networks:
     - backend
