version: '3'
services:
    dkwebsite-service:
        container_name: dkwebsite
        build: .

    nginx:
        #container_name: reverse-proxy
        restart: unless-stopped
        image: nginx
        ports:
         - "443:443"
         - "80:80"
         #- "3306:3306"
        volumes:
         - ./data/nginx:/etc/nginx/conf.d
         - ./data/certbot/conf:/etc/letsencrypt
         - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        
    certbot:
        image: j0nnylester/certbot
        restart: unless-stopped
        volumes:
         - ./data/certbot/conf:/etc/letsencrypt
         - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
         
    db:
        container_name: mysql-db
        image: hypriot/rpi-mysql
        env_file: /home/pi/website/config/db/.env
        volumes:
         - /home/pi/website/db/storage:/var/lib/mysql