version: '3.4'
networks:
  backend:
    external: true

services:
  sensors:
    build:
      context: Sensors/RpiREST/
      dockerfile: Dockerfile
    networks:
     - backend
    privileged: true
    ports:
    - target: 80
      published: 82
      protocol: tcp
      mode: host
