version: '3.4'
networks:
  frontend:
    external: true
  backend:
    external: true

services:
  sensors:
    build:
      context: Sensor/RaspberryREST/
      dockerfile: Dockerfile
    networks:
     - backend
    privileged: true

  primary:
    build:
      context: Website/Primary/
      dockerfile: Dockerfile
    networks:
     - frontend
     - backend
