version: '3'
services:
    dkwebsite-service:
        container_name: dkwebsite
        build: .

    reverse-proxy:
        container_name: reverse-proxy
        image: nginx
        ports:
         - "443:443"
         - "80:80"
         - "3306:3306"
        volumes:
         - /home/pi/website/config/proxy.conf:/etc/nginx/conf.d/default.conf
         
    db:
        container_name: mysql-db
        image: hypriot/rpi-mysql
        env_file: /home/pi/website/config/db/.env
        volumes:
         - /home/pi/website/db/storage:/var/lib/mysql